/*
  * Generated by cppsrc.sh
  * On 2016-01-01 18:40:09,38
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Builder_v1_H
#define Builder_v1_H

namespace StarVFS {
namespace RDC {

class Builder_v1 : public Builder {
public:
 	Builder_v1();
 	virtual ~Builder_v1();

	virtual Headers::VersionValue GetVersion() const override { return Headers::VersionValue(1); }
protected:

	bool WriteBlockAtEnd(const char *data, Headers::Version_1::Size size, Headers::Version_1::DataBlock &blockdesc);

	virtual void Reset() override;
	virtual bool WriteFileFooter() override;
	virtual bool WriteSectionTable() override;
private:
	struct PrivateData;
	std::unique_ptr<PrivateData> m_Data;
};

} //namespace RDC 
} //namespace StarVFS 

#endif
