/*
  * Generated by cppsrc.sh
  * On 
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#pragma once
#ifndef cli_H
#define cli_H

#include "svfs.h"
#include "luainterface.h"

class CLI {
public:
	CLI(SharedLua Lua);
	CLI(const CLI&) = delete;

	CLI& operator=(const CLI&) = delete;

	bool Enter(SVFS& svfs);
private:
	SharedLua m_Lua;
	bool m_CanContinue;

	bool InstallApi();
	void Loop();

	//for lua
	void Exit(int ec);

};

#endif
