/*
  * Generated by cppsrc.sh
  * On 
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef luainterface_H
#define luainterface_H

#include <lua/lua.hpp>
#include <LuaBridge/LuaBridge.h>

struct LuaDeleter {
	void operator()(lua_State *l) {
		lua_close(l);
	}
};

struct Lua;
using SharedLua = std::shared_ptr<Lua>;

struct Lua {
	static SharedLua New() {
		struct L : public Lua { };
		return std::make_shared<L>();
	}

	lua_State *GetState() { return m_Lua.get(); }

	bool Initialize();
protected:
	Lua();
	virtual ~Lua() { }
private:
	std::unique_ptr<lua_State, LuaDeleter> m_Lua;
};

#endif
