/*
  * Generated by cppsrc.sh
  * On 2015-12-12  9:44:59,49
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef RemoteModule_H
#define RemoteModule_H

namespace StarVFS {
namespace Modules {

class RemoteModule : public iModule {
public:
	RemoteModule(StarVFS *svfs, int port = 0);
 	virtual ~RemoteModule();
private: 
	volatile bool m_CanRun, m_ThreadRunning;
	int m_Port;
	void ThreadMain();
	struct Connection;
};

} //namespace Modules 
} //namespace StarVFS 

#endif
