/*
  * Generated by cppsrc.sh
  * On 2015-12-12  9:44:49,30
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef iModule_H
#define iModule_H

namespace StarVFS {
namespace Modules {

class iModule {
public:
 	iModule(StarVFS *svfs);
 	virtual ~iModule();

	StarVFS* GetVFS() { return m_SVFS; }
private: 
	StarVFS *m_SVFS;
};

} //namespace Modules 
} //namespace StarVFS 

#endif
