/*
  * Generated by cppsrc.sh
  * On 2015-12-12  9:44:59,49
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Remote_H
#define Remote_H

namespace StarVFS {
namespace Modules {

class Remote : public iModule {
public:
 	Remote(StarVFS *svfs, int port = 0);
 	virtual ~Remote();
private: 
	volatile bool m_CanRun, m_ThreadRunning;
	void ThreadMain();
	struct Connection;
};

} //namespace Modules 
} //namespace StarVFS 

#endif
