/*
  * Generated by cppsrc.sh
  * On 2015-12-10 18:22:05,47
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Hash_H
#define Hash_H

namespace StarVFS {

struct Murmur3Hash32 {
	static FilePathHash Hash(const char *data, size_t len);
};

using FilePathHashAlgorithm = Murmur3Hash32;

} //namespace StarVFS 

#endif
