/*
  * Generated by cppsrc.sh
  * On 2015-12-14  7:26:50,12
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include "HashFileTable.h"

namespace StarVFS {

HashFileTable::HashFileTable() {
}

HashFileTable::~HashFileTable() {
}

} //namespace StarVFS 

