/*
  * Generated by cppsrc.sh
  * On 2015-12-10 18:22:05,47
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef Hash_H
#define Hash_H

namespace StarVFS {

using FileIDHash = uint32_t;

struct Murmur3Hash32 {
	static FileIDHash Hash(const char *data, size_t len);
};

using FileIDHashAlgorithm = Murmur3Hash32;

} //namespace StarVFS 

#endif
