/*
  * Generated by cppsrc.sh
  * On 2015-12-22 21:08:18,29
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include "../StarVFSInternal.h"

namespace StarVFS {
namespace Containers {

FileTableInterface::FileTableInterface(FileTable *Owner, ContainerID cid):
		m_Owner(Owner), m_CID(cid) {
}

FileTableInterface::~FileTableInterface() {
}

} //namespace Containers 
} //namespace StarVFS 
