/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:51:26,41
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#include "../StarVFSInternal.h"
#include "RDCContainer.h"

namespace StarVFS {
namespace Containers {

RDCContainer::RDCContainer() {
}

RDCContainer::~RDCContainer() {
}

} //namespace Containers 
} //namespace StarVFS 

