/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:51:26,41
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef RDCContainer_H
#define RDCContainer_H

namespace StarVFS {
namespace Containers {

class RDCContainer : public iContainer {
public:
 	RDCContainer();
 	virtual ~RDCContainer();
protected:
private: 
};

} //namespace Containers 
} //namespace StarVFS 

#endif
