/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:51:26,41
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef RDCContainer_H
#define RDCContainer_H

namespace StarVFS {
namespace Containers {

class RDCContainer : public iContainer {
public:
 	RDCContainer(FileTableInterface *fti);
 	virtual ~RDCContainer();

	virtual FileID GetFileCount() const override;
	virtual bool ReloadContainer() override;
	virtual bool RegisterContent() const override;

	virtual bool GetFileData(FileID ContainerFID, CharTable &out, FileSize *DataSize) const override;

	virtual const String& GetFileName() const override { return ""; }
	virtual RWMode GetRWMode() const override { return RWMode::RW; };
protected:
private: 
};

} //namespace Containers 
} //namespace StarVFS 

#endif
