/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:58:58,71
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef iExporter_H
#define iExporter_H

namespace StarVFS {
namespace Exporters {

class iExporter {
public:
 	iExporter();
 	virtual ~iExporter();
protected:
private: 
};

} //namespace Exporters 
} //namespace StarVFS 

#endif
