/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:58:58,71
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef iExporter_H
#define iExporter_H

namespace StarVFS {
namespace Exporters {

enum class ExportResult {
	Sucess,
	FatalError,
	LocalFileWriteError,
};

class iExporter : public AttributeMap {
public:
 	iExporter(StarVFS *svfs);
 	virtual ~iExporter();

	virtual ExportResult DoExport(const String &VFSBase, const String &LocalFileName) const = 0;
protected:
	StarVFS* GetSVFS() const { return m_SVFS; }
private: 
	StarVFS *m_SVFS;
};

} //namespace Exporters 
} //namespace StarVFS 

#endif
