/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:58:58,71
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include "../StarVFSInternal.h"

namespace StarVFS {
namespace Exporters {

iExporter::iExporter(StarVFS *svfs): m_SVFS(svfs) {
}

iExporter::~iExporter() {
	int i = 0;
}

//-------------------------------------------------------------------------------------------------

} //namespace Exporters 
} //namespace StarVFS 
