/*
  * Generated by cppsrc.sh
  * On 2015-12-17 22:12:37,21
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/

#pragma once
#ifndef InternalExporter_H
#define InternalExporter_H

namespace StarVFS {
namespace Exporters {

class InternalExporter : public iExporter {
public:
 	InternalExporter(StarVFS *svfs);
 	virtual ~InternalExporter();

	virtual ExportResult DoExport(const String &VFSBase, const String &LocalFileName) const;

	void SetNamespace(const CString n) { m_Namespace = n; }
	void SetNamespace(const String &n) { m_Namespace = n; }

	void SetName(const CString n) { m_Name = n; }
	void SetName(const String &n) { m_Name = n; }
protected:
private: 
	struct ExporterImpl;
	String m_Namespace;
	String m_Name;
};

} //namespace Exporters 
} //namespace StarVFS 

#endif
