/*
  * Generated by cppsrc.sh
  * On 2015-12-17 21:59:15,19
  * by Paweu
*/
/*--END OF HEADER BLOCK--*/
#include "../StarVFSInternal.h"
#include "RDCExporter.h"

namespace StarVFS {
namespace Exporters {

RDCExporter::RDCExporter() {

}

RDCExporter::~RDCExporter() {

}

} //namespace Exporters 
} //namespace StarVFS 
